name: Build SunamoTest

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoTest
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoTest/SunamoTest.csproj

    - name: Build
      run: dotnet build SunamoTest/SunamoTest.csproj --configuration Release --no-restore

  test:
    name: Test SunamoTest.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoTest.Tests/SunamoTest.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoTest.Tests/SunamoTest.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoTest.Tests/SunamoTest.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
